name: lottie_thorvg
description: This package has been deprecated.
version: 0.0.2
repository: https://github.com/tinyjin/lottie-thorvg

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      # linux:
      #   ffiPlugin: true
      # macos:
      #   ffiPlugin: true
      # windows:
      #   ffiPlugin: true
